
service: my-service

variablesResolutionMode: 20210326

# package:
#   individually: true

provider:
  name: aws
  region: us-west-2
  lambdaHashingVersion: 20201221
  runtime: nodejs14.x

functions:
  myFunc:
    handler: src/handler.handler
    environment:
      AUTH_KEY: ${self:custom.envVars.AUTH_KEY}
    events:
      - http:
         method: ANY
         path: /
      - http:
         method: ANY
         path: '{proxy+}'

custom:
  envVars: ${file(config-env-for-serverless.js)}
  webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    includeModules: false # Node modules configuration for packaging
    packager: 'npm' # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore

plugins:
  - serverless-offline
  - serverless-webpack